In [6]:
import os
import pandas as pd
import numpy as np
base_url = '../../practical-jupyter/anime/'

In [7]:
anime_csv = os.path.join(base_url, 'anime.csv')
df = pd.read_csv(anime_csv)

df.loc[df['episodes'] == 'Unknown'].head()

,anime_id,name,genre,type,episodes,rating,members
73,21,One Piece,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",TV,Unknown,8.58,504862
248,235,Detective Conan,"Adventure, Comedy, Mystery, Police, Shounen",TV,Unknown,8.25,114702
607,1735,Naruto: Shippuuden,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,Unknown,7.94,533578
993,33157,Tanaka-kun wa Itsumo Kedaruge Specials,"Comedy, School, Slice of Life",Special,Unknown,7.72,5400
1226,21639,Yu☆Gi☆Oh! Arc-V,"Action, Fantasy, Game, Shounen",TV,Unknown,7.61,17571

In [9]:
df.where(df['rating'] < 9.2).head()

,anime_id,name,genre,type,episodes,rating,members
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9253.0,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572.0
4,9969.0,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266.0

In [11]:
df.loc[74, 'episodes'] = np.nan
df.loc[74, 'episodes']

nan

In [15]:
# episodesがUnknownの場合に　NaN に変更
df.loc[df['episodes'] == 'Unknown', 'episodes'] = np.nan
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
5,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,"Comedy, Drama, School, Shounen, Sports",TV,10,9.15,93351
6,11061,Hunter x Hunter (2011),"Action, Adventure, Shounen, Super Power",TV,148,9.13,425855
7,820,Ginga Eiyuu Densetsu,"Drama, Military, Sci-Fi, Space",OVA,110,9.11,80679
8,15335,Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",Movie,1,9.10,72534
9,15417,Gintama&#039;: Enchousen,"Action, Comedy, Historical, Parody, Samurai, S...",TV,13,9.11,81109
10,4181,Clannad: After Story,"Drama, Fantasy, Romance, Slice of Life, Supern...",TV,24,9.06,456749
11,28851,Koe no Katachi,"Drama, School, Shounen",Movie,1,9.05,102733
12,918,Gintama,"Action, Comedy, Historical, Parody, Samurai, S...",TV,201,9.04,336376
13,2904,Code Geass: Hangyaku no Lelouch R2,"Action, Drama, Mecha, Military, Sci-Fi, Super ...",TV,25,8.98,572888
14,28891,Haikyuu!! Second Season,"Comedy, Drama, School, Shounen, Sports",TV,25,8.93,179342
15,199,Sen to Chihiro no Kamikakushi,"Adventure, Drama, Supernatural",Movie,1,8.93,466254
16,23273,Shigatsu wa Kimi no Uso,"Drama, Music, Romance, School, Shounen",TV,22,8.92,416397
17,24701,Mushishi Zoku Shou 2nd Season,"Adventure, Fantasy, Historical, Mystery, Seine...",TV,10,8.88,75894
18,12355,Ookami Kodomo no Ame to Yuki,"Fantasy, Slice of Life",Movie,1,8.84,226193
19,1575,Code Geass: Hangyaku no Lelouch,"Action, Mecha, Military, School, Sci-Fi, Super...",TV,25,8.83,715151
20,263,Hajime no Ippo,"Comedy, Drama, Shounen, Sports",TV,75,8.83,157670
21,44,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,"Action, Drama, Historical, Martial Arts, Roman...",OVA,4,8.83,129307
22,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824
23,30276,One Punch Man,"Action, Comedy, Parody, Sci-Fi, Seinen, Super ...",TV,12,8.82,552458
24,164,Mononoke Hime,"Action, Adventure, Fantasy",Movie,1,8.81,339556
25,7311,Suzumiya Haruhi no Shoushitsu,"Comedy, Mystery, Romance, School, Sci-Fi, Supe...",Movie,1,8.81,240297
26,17074,Monogatari Series: Second Season,"Comedy, Mystery, Romance, Supernatural, Vampire",TV,26,8.80,205959
27,21939,Mushishi Zoku Shou,"Adventure, Fantasy, Historical, Mystery, Seine...",TV,10,8.80,101351
28,457,Mushishi,"Adventure, Fantasy, Historical, Mystery, Seine...",TV,26,8.78,300030
29,2001,Tengen Toppa Gurren Lagann,"Action, Adventure, Comedy, Mecha, Sci-Fi",TV,27,8.78,562962
...,...,...,...,...,...,...,...
10456,33036,Suki ni Naru Sono Shunkan wo.: Kokuhaku Jikkou...,"Comedy, Drama, Romance, School",Movie,1,NaN,10668
10457,33013,Super Lovers OVA,"Comedy, Drama, Romance, Shounen Ai",OVA,1,NaN,5210
10458,27783,Sword Gai (TV),Seinen,TV,NaN,NaN,6474
10459,34086,Tales of Zestiria the X (2017),"Action, Adventure, Fantasy",TV,12,NaN,10848
10460,34310,Tamagotchi Movie: Tanpen Himitsu no Otodoke Da...,NaN,Movie,1,NaN,51
10461,33308,Tantei Opera Milky Holmes: Fun Fun Party Night...,"Comedy, Mystery, Super Power",Special,1,NaN,610
10462,34177,Tenshi no 3P!,"Music, School, Slice of Life",TV,NaN,NaN,359
10463,34449,THE REFLECTION,"Action, Super Power",TV,NaN,NaN,242
10464,32596,The Snack World (TV),"Adventure, Comedy, Fantasy, Kids",TV,NaN,NaN,107
10465,34416,The Snack World: Hitogirai no Renny,"Adventure, Comedy, Fantasy, Kids",Movie,1,NaN,36
10466,33473,Tokyo Futago Athletic,"Comedy, Sports",ONA,8,NaN,75
10467,21305,Trick or Alice,Fantasy,OVA,NaN,NaN,4481
10468,23275,Tsubu★Doll,Music,OVA,5,NaN,1060
10469,34474,Tsukipro The Animation,NaN,TV,NaN,NaN,843
10470,34498,"Uchiage Hanabi, Shita kara Miru ka? Yoko kara ...",Drama,Movie,1,NaN,531
10471,34076,Uchouten Kazoku 2,"Comedy, Drama, Fantasy, Slice of Life",TV,NaN,NaN,5934
10472,33064,Uchuu Senkan Yamato 2202: Ai no Senshi-tachi,"Action, Drama, Military, Sci-Fi, Space",OVA,NaN,NaN,2058
10473,33478,UQ Holder!,"Action, Fantasy, Magic, Sci-Fi, Shounen",NaN,NaN,NaN,2341
10474,32924,Urara Meirochou,"Comedy, Seinen, Slice of Life",TV,NaN,NaN,4305
10475,32012,Utakata Overdrive,"Fantasy, Music",OVA,1,NaN,649
10476,34522,"Wake Up, Girls! Shin Shou","Drama, Music",TV,NaN,NaN,381
10477,34022,Whistle! (ONA),"School, Shounen, Sports",ONA,NaN,NaN,381
10478,34467,Yami Shibai 4th Season,"Dementia, Horror, Supernatural",TV,NaN,NaN,1838
10479,32615,Youjo Senki,"Magic, Military",TV,NaN,NaN,6652
10480,32222,Youkai Watch Movie 3: Soratobu Kujira to Doubl...,"Comedy, Kids, Supernatural",Movie,1,NaN,237
10481,34471,Youkai Watch Movie 4,"Comedy, Kids, Supernatural",Movie,1,NaN,169
10482,34284,Yuuki Yuuna wa Yuusha de Aru: Washio Sumi no Shou,"Drama, Fantasy, Magic, Slice of Life",TV,6,NaN,2593
10483,34445,Yuuki Yuuna wa Yuusha de Aru: Yuusha no Shou,"Drama, Fantasy, Magic, Slice of Life",TV,6,NaN,4439
10484,33035,Yuyushiki Special,NaN,Special,1,NaN,2294
10485,33390,Zunda Horizon,NaN,Movie,1,NaN,160

In [16]:
# episodesがNaN(欠損値)の場合のみ抽出
df.loc[df['episodes'].isnull()].head()

,anime_id,name,genre,type,episodes,rating,members
73,21,One Piece,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",TV,NaN,8.58,504862
74,801,Ghost in the Shell: Stand Alone Complex 2nd GIG,"Action, Mecha, Military, Mystery, Police, Sci-...",TV,NaN,8.57,113993
248,235,Detective Conan,"Adventure, Comedy, Mystery, Police, Shounen",TV,NaN,8.25,114702
607,1735,Naruto: Shippuuden,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,NaN,7.94,533578
993,33157,Tanaka-kun wa Itsumo Kedaruge Specials,"Comedy, School, Slice of Life",Special,NaN,7.72,5400

In [18]:
# 欠損値を持ったデータを除外,73,74がなくなる
# 非破壊的操作
df.dropna().loc[70:].head()

,anime_id,name,genre,type,episodes,rating,members
70,578,Hotaru no Haka,"Drama, Historical",Movie,1,8.58,174878
71,16894,Kuroko no Basket 2nd Season,"Comedy, School, Shounen, Sports",TV,25,8.58,243325
72,5028,Major S5,"Comedy, Drama, Romance, Sports",TV,25,8.58,28653
75,31933,JoJo no Kimyou na Bouken: Diamond wa Kudakenai,"Action, Adventure, Comedy, Drama, Shounen, Sup...",TV,39,8.57,74074
76,5205,Kara no Kyoukai 7: Satsujin Kousatsu (Kou),"Action, Mystery, Romance, Supernatural, Thriller",Movie,1,8.57,95658

In [19]:
# 破壊的操作
df.dropna(inplace=True)
df.loc[70:].head()

,anime_id,name,genre,type,episodes,rating,members
70,578,Hotaru no Haka,"Drama, Historical",Movie,1,8.58,174878
71,16894,Kuroko no Basket 2nd Season,"Comedy, School, Shounen, Sports",TV,25,8.58,243325
72,5028,Major S5,"Comedy, Drama, Romance, Sports",TV,25,8.58,28653
75,31933,JoJo no Kimyou na Bouken: Diamond wa Kudakenai,"Action, Adventure, Comedy, Drama, Shounen, Sup...",TV,39,8.57,74074
76,5205,Kara no Kyoukai 7: Satsujin Kousatsu (Kou),"Action, Mystery, Romance, Supernatural, Thriller",Movie,1,8.57,95658

In [20]:
# Seriesのデータ型確認
df['anime_id'].dtype

dtype('int64')

In [21]:
# DataFrameのデータ型確認
df.dtypes

anime_id      int64
name         object
genre        object
type         object
episodes     object
rating      float64
members       int64
dtype: object

In [23]:
# 型変換
pd.options.display.max_rows = 10 #出力制限
df['episodes'].astype(np.int64)

0         1
1        64
2        51
3        24
4        51
         ..
10272     1
10273    23
10274     1
10275     1
10276    32
Name: episodes, Length: 10075, dtype: int64

In [24]:
df.astype({'episodes': np.int64, 'rating': np.float64})

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
10272,11095,Zouressha ga Yatte Kita,Adventure,Movie,1,6.06,78
10273,7808,Zukkoke Knight: Don De La Mancha,"Adventure, Comedy, Historical, Romance",TV,23,6.47,172
10274,28543,Zukkoke Sannin-gumi no Hi Asobi Boushi Daisakusen,"Drama, Kids",OVA,1,5.83,50
10275,18967,Zukkoke Sannin-gumi: Zukkoke Jikuu Bouken,"Comedy, Historical, Sci-Fi",OVA,1,6.13,76
10276,13455,Zumomo to Nupepe,Comedy,TV,32,7.00,120

In [25]:
#astypeは非破壊的操作であることを確認
df.dtypes

anime_id      int64
name         object
genre        object
type         object
episodes     object
rating      float64
members       int64
dtype: object

In [26]:
# 型を書き換える場合は代入する
df['episodes'] = df['episodes'].astype(np.int64)
df.dtypes

anime_id      int64
name         object
genre        object
type         object
episodes      int64
rating      float64
members       int64
dtype: object

In [27]:
df.sort_values('rating', ascending=False).head()

,anime_id,name,genre,type,episodes,rating,members
9846,33662,Taka no Tsume 8: Yoshida-kun no X-Files,"Comedy, Parody",Movie,1,10.00,13
8985,23005,Mogura no Motoro,Slice of Life,Movie,1,9.50,62
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
8474,33607,Kahei no Umi,Historical,Movie,1,9.33,44
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665

In [29]:
import html

# mapメソッドを使うことで、Seriesの値ごとに関数を適用できる
print(df['name'].head())
print(df['name'].map(html.unescape).head())

0                      Kimi no Na wa.
1    Fullmetal Alchemist: Brotherhood
2                            Gintama°
3                         Steins;Gate
4                       Gintama&#039;
Name: name, dtype: object
0                      Kimi no Na wa.
1    Fullmetal Alchemist: Brotherhood
2                            Gintama°
3                         Steins;Gate
4                            Gintama'
Name: name, dtype: object

In [30]:
# applyメソッドではDataFrameの列または行に関数を適用
# 列の場合
df.apply(len)

anime_id    10075
name        10075
genre       10075
type        10075
episodes    10075
rating      10075
members     10075
dtype: int64

In [31]:
# 行の場合
df.apply(len, axis=1).head()

0    7
1    7
2    7
3    7
4    7
dtype: int64

In [32]:
df.apply(type)

anime_id    <class 'pandas.core.series.Series'>
name        <class 'pandas.core.series.Series'>
genre       <class 'pandas.core.series.Series'>
type        <class 'pandas.core.series.Series'>
episodes    <class 'pandas.core.series.Series'>
rating      <class 'pandas.core.series.Series'>
members     <class 'pandas.core.series.Series'>
dtype: object

In [33]:
# applyメソッドにはラベルを指定
# name列とgenre列の文字数を合計
df.apply(lambda x: len(x['name']) + len(x['genre']), axis=1).head()

0    50
1    91
2    68
3    27
4    73
dtype: int64

In [34]:
# DataFrameの各値に対してlen()を適用
df[['name', 'genre']].applymap(len).head()

   name  genre
0    14     36
1    32     59
2     8     60
3    11     16
4    13     60

In [35]:
df[['name', 'genre']]

,name,genre
0,Kimi no Na wa.,"Drama, Romance, School, Supernatural"
1,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili..."
2,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S..."
3,Steins;Gate,"Sci-Fi, Thriller"
4,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S..."
...,...,...
10272,Zouressha ga Yatte Kita,Adventure
10273,Zukkoke Knight: Don De La Mancha,"Adventure, Comedy, Historical, Romance"
10274,Zukkoke Sannin-gumi no Hi Asobi Boushi Daisakusen,"Drama, Kids"
10275,Zukkoke Sannin-gumi: Zukkoke Jikuu Bouken,"Comedy, Historical, Sci-Fi"
10276,Zumomo to Nupepe,Comedy